name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build Docker image
      run: docker build -t saw-app -f environments/Dockerfile .

    - name: Run tests in Docker container
      run: |
        docker run --rm saw-app python -m unittest discover -s saw -p '*_test.py'